# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3f46be6fe035b6ba6a254a3193e6a5a59e10c4f568de96736185e534e9fccaa67a88aa9b69b7901f8487983dd80c36bbf880babb54552b8ce9ff5952e90e5fb

test:
  secret_key_base: ad389bc1dc1d0123b06462404fa6fb4f8bdf301acfedeec5bb528d2a55671de54288d2702b1674f4c97dada78dfbb0035405756fd6cf29d444ae44e9a76ce727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
